In [1]:
# Import our dependencies
import pandas as pd
import matplotlib as plt
import sklearn as skl
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [56]:
# Import our input dataset
ev_location_df = pd.read_csv('EVStation_income.csv')
ev_location_df.head()

,county,statecode_of_county,access_code,fuel_type_code,statecode_of_county-2,income_yr_2019,income_yr_2020,income_yr_2021
0,Los Angeles,CA,public,ELEC,CA,635759588,684663140,728772915
1,Los Angeles,CA,public,ELEC,CA,635759588,684663140,728772915
2,San Diego,CA,public,ELEC,CA,206231115,223652407,238691713
3,Los Angeles,CA,public,ELEC,CA,635759588,684663140,728772915
4,Riverside,CA,public,ELEC,CA,104149463,115570337,125820553

In [57]:
ev_location_df.shape

(202248, 8)

In [20]:
# Generate our categorical variable list
ev_location = ev_location_df.dtypes[ev_location_df.dtypes == "object"].index.tolist()

In [21]:
# Check the number of unique values in each column
ev_location_df[ev_location].nunique()

county                   1246
statecode_of_county        54
access_code                 1
fuel_type_code              2
statecode_of_county-2      50
dtype: int64

In [22]:
#drop extra statecode of county 

ev_location_df = ev_location_df.drop(columns=['statecode_of_county-2'])

In [23]:
ev_location_df.head()

,county,statecode_of_county,access_code,fuel_type_code,income_yr_2019,income_yr_2020,income_yr_2021
0,Los Angeles,CA,public,ELEC,635759588,684663140,728772915
1,Los Angeles,CA,public,ELEC,635759588,684663140,728772915
2,San Diego,CA,public,ELEC,206231115,223652407,238691713
3,Los Angeles,CA,public,ELEC,635759588,684663140,728772915
4,Riverside,CA,public,ELEC,104149463,115570337,125820553

In [24]:
# Generate our categorical variable list
ev_location = ev_location_df.dtypes[ev_location_df.dtypes == "object"].index.tolist()

In [25]:
# Check the number of unique values in each column
ev_location_df[ev_location].nunique()

county                 1246
statecode_of_county      54
access_code               1
fuel_type_code            2
dtype: int64

In [26]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(ev_location_df[ev_location]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names_out(ev_location)
encode_df.head()

,county_Abbeville,county_Acadia,county_Accomack,county_Ada,county_Adair,county_Adams,county_Addison,county_Aiken,county_Aitkin,county_Alachua,...,statecode_of_county_UT,statecode_of_county_VA,statecode_of_county_VT,statecode_of_county_WA,statecode_of_county_WI,statecode_of_county_WV,statecode_of_county_WY,access_code_public,fuel_type_code_ELEC,fuel_type_code_HY
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [27]:
# Merge one-hot encoded features and drop the originals
ev_location_df = ev_location_df.merge(encode_df,left_index=True, right_index=True)
ev_location_df = ev_location_df.drop(ev_location,1)
ev_location_df.head()

C:\Users\bbbnne\Anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,income_yr_2019,income_yr_2020,income_yr_2021,county_Abbeville,county_Acadia,county_Accomack,county_Ada,county_Adair,county_Adams,county_Addison,...,statecode_of_county_UT,statecode_of_county_VA,statecode_of_county_VT,statecode_of_county_WA,statecode_of_county_WI,statecode_of_county_WV,statecode_of_county_WY,access_code_public,fuel_type_code_ELEC,fuel_type_code_HY
0,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,206231115,223652407,238691713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,104149463,115570337,125820553,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [38]:
ev_location_df.head()

,income_yr_2019,income_yr_2020,income_yr_2021,county_Abbeville,county_Acadia,county_Accomack,county_Ada,county_Adair,county_Adams,county_Addison,...,statecode_of_county_UT,statecode_of_county_VA,statecode_of_county_VT,statecode_of_county_WA,statecode_of_county_WI,statecode_of_county_WV,statecode_of_county_WY,access_code_public,fuel_type_code_ELEC,fuel_type_code_HY
0,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,206231115,223652407,238691713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,104149463,115570337,125820553,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [40]:
# Split our preprocessed data into our features and target arrays
y = ev_location_df["fuel_type_code_ELEC"].values
X = ev_location_df.drop(["fuel_type_code_ELEC"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

C:\Users\bbbnne\Anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [41]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [42]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 10448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 10,499
Trainable params: 10,499
Non-trainable params: 0
_________________________________________________________________

In [43]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [44]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
4741/4741 [==============================] - 9s 2ms/step - loss: 61.5603 - accuracy: 0.9963
Epoch 2/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0239 - accuracy: 0.9988
Epoch 3/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0105 - accuracy: 0.9988
Epoch 4/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0095 - accuracy: 0.9988
Epoch 5/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0095 - accuracy: 0.9988
Epoch 6/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 7/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 8/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 9/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 10/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 11/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 12/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 13/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 14/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 15/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 16/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 17/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 18/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 19/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 20/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 21/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 22/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 23/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 24/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 25/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 26/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 27/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 28/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 29/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 30/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 31/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 32/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 33/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 34/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 35/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 36/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 37/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 38/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 39/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 40/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 41/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 42/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 43/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 44/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 45/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 46/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 47/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 48/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 49/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 50/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 51/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 52/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 53/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 54/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 55/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 56/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 57/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 58/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 59/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 60/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 61/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 62/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 63/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 64/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 65/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 66/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 67/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 68/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 69/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 70/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 71/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 72/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 73/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 74/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 75/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 76/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 77/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 78/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 79/100

4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 80/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 81/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 82/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 83/100
4741/4741 [==============================] - 7s 1ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 84/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 85/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 86/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 87/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 88/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 89/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 90/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 91/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 92/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 93/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 94/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 95/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 96/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 97/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 98/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 99/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 100/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988

In [45]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

1581/1581 - 2s - loss: 0.0085 - accuracy: 0.9989 - 2s/epoch - 1ms/step
Loss: 0.008515470661222935, Accuracy: 0.9989122152328491

In [46]:
#test for HY charging stations 
ev_location_df.head()

,income_yr_2019,income_yr_2020,income_yr_2021,county_Abbeville,county_Acadia,county_Accomack,county_Ada,county_Adair,county_Adams,county_Addison,...,statecode_of_county_UT,statecode_of_county_VA,statecode_of_county_VT,statecode_of_county_WA,statecode_of_county_WI,statecode_of_county_WV,statecode_of_county_WY,access_code_public,fuel_type_code_ELEC,fuel_type_code_HY
0,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,206231115,223652407,238691713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,635759588,684663140,728772915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,104149463,115570337,125820553,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [47]:
# Split our preprocessed data into our features and target arrays
y = ev_location_df["fuel_type_code_HY"].values
X = ev_location_df.drop(["fuel_type_code_HY"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

C:\Users\bbbnne\Anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [50]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [51]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn_2 = tf.keras.models.Sequential()

# First hidden layer
nn_2.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 8)                 10448

 dense_7 (Dense)             (None, 5)                 45

 dense_8 (Dense)             (None, 1)                 6

=================================================================
Total params: 10,499
Trainable params: 10,499
Non-trainable params: 0
_________________________________________________________________

In [52]:
# Compile the model
nn_2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
# Train the model
fit_model = nn_2.fit(X_train,y_train,epochs=100)

Epoch 1/100
4741/4741 [==============================] - 9s 2ms/step - loss: 1926.6638 - accuracy: 0.9934
Epoch 2/100
4741/4741 [==============================] - 8s 2ms/step - loss: 793.0038 - accuracy: 0.9937
Epoch 3/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0652 - accuracy: 0.9988
Epoch 4/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0133 - accuracy: 0.9988
Epoch 5/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0097 - accuracy: 0.9988
Epoch 6/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0095 - accuracy: 0.9988
Epoch 7/100
4741/4741 [==============================] - 14s 3ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 8/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 9/100
4741/4741 [==============================] - 9s 2ms/step - loss: 6.2169 - accuracy: 0.9986
Epoch 10/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 11/100
4741/4741 [==============================] - 12s 3ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 12/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 13/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 14/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 15/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 16/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0679 - accuracy: 0.9988
Epoch 17/100
4741/4741 [==============================] - 12s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 18/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 19/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 20/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 21/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 22/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 23/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 24/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 25/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 26/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 27/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 28/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 29/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 30/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 31/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 32/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 33/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 34/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 35/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 36/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 37/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 38/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 39/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 40/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 41/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 42/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 43/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 44/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 45/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 46/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 47/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 48/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 49/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 50/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 51/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 52/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 53/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 54/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 55/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 56/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 57/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 58/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 59/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 60/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 61/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 62/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 63/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 64/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 65/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 66/100
4741/4741 [==============================] - 10s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 67/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 68/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 69/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 70/100
4741/4741 [==============================] - 9s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 71/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 72/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 73/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 74/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 75/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 76/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 77/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 78/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 79/100

4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 80/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 81/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 82/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 83/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 84/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 85/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 86/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 87/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 88/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 89/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 90/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 91/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 92/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 93/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 94/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 95/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 96/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 97/100
4741/4741 [==============================] - 7s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 98/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 99/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988
Epoch 100/100
4741/4741 [==============================] - 8s 2ms/step - loss: 0.0094 - accuracy: 0.9988

In [55]:
#Evaluate the model using the test data
model_loss, model_accuracy = nn_2.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

1581/1581 - 2s - loss: 0.0085 - accuracy: 0.9989 - 2s/epoch - 1ms/step
Loss: 0.008517952635884285, Accuracy: 0.9989122152328491