In [1]:
#Export NY and MI to Postgres

In [2]:
# Import our dependencies
import pandas as pd
import numpy as np
#import config as creds
import psycopg2
from sqlalchemy import create_engine

In [3]:
#create function to read data 
def read_data_from_file(name):
    data = []
    with open(name) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')

        # skip the first row
        next(csv_reader)
        for row in csv_reader:
            data.append(row)
    return data

In [4]:
#read county NY csv files back in 

ny_counties_df = pd.read_csv('ny_ev_registrations_public_updated.csv', dtype=object,)

ny_counties_df

              County Registration Valid Date          Vehicle Name
0        Westchester                 3/27/19         Tesla Model 3
1        Westchester                12/24/18         Tesla Model 3
2        Westchester                 12/4/18         Tesla Model 3
3        Westchester                 12/1/18         Tesla Model 3
4        Westchester                11/29/18         Tesla Model 3
...              ...                     ...                   ...
1048570      Suffolk                 12/1/16  Toyota Prius Plug-in
1048571       Monroe                 3/26/18  Toyota Prius Plug-in
1048572       Ulster                 1/23/18  Toyota Prius Plug-in
1048573         Erie                 5/31/17  Toyota Prius Plug-in
1048574     Rockland                 4/13/17  Toyota Prius Plug-in

[1048575 rows x 3 columns]

In [5]:
ny_counties_df.dtypes

County                     object
Registration Valid Date    object
Vehicle Name               object
dtype: object

In [6]:
# altering the DataFrame
# new_ny_county_df = ny_counties_df

In [7]:
# keeping/adding relevant columns and renaming the columns
ny_counties_df["statecode_of_county"] = "NY"
ny_counties_df = ny_counties_df[['statecode_of_county','County',"Registration Valid Date","Vehicle Name"]]
ny_counties_df.columns = ['statecode_of_county','county', 'registration_date', 'vehicle_name']
ny_counties_df

,statecode_of_county,county,registration_date,vehicle_name
0,NY,Westchester,3/27/19,Tesla Model 3
1,NY,Westchester,12/24/18,Tesla Model 3
2,NY,Westchester,12/4/18,Tesla Model 3
3,NY,Westchester,12/1/18,Tesla Model 3
4,NY,Westchester,11/29/18,Tesla Model 3
...,...,...,...,...
1048570,NY,Suffolk,12/1/16,Toyota Prius Plug-in
1048571,NY,Monroe,3/26/18,Toyota Prius Plug-in
1048572,NY,Ulster,1/23/18,Toyota Prius Plug-in
1048573,NY,Erie,5/31/17,Toyota Prius Plug-in
1048574,NY,Rockland,4/13/17,Toyota Prius Plug-in

In [8]:
ny_counties_df["registration_date"] = pd.to_datetime(ny_counties_df["registration_date"])

In [9]:
ny_counties_df

,statecode_of_county,county,registration_date,vehicle_name
0,NY,Westchester,2019-03-27,Tesla Model 3
1,NY,Westchester,2018-12-24,Tesla Model 3
2,NY,Westchester,2018-12-04,Tesla Model 3
3,NY,Westchester,2018-12-01,Tesla Model 3
4,NY,Westchester,2018-11-29,Tesla Model 3
...,...,...,...,...
1048570,NY,Suffolk,2016-12-01,Toyota Prius Plug-in
1048571,NY,Monroe,2018-03-26,Toyota Prius Plug-in
1048572,NY,Ulster,2018-01-23,Toyota Prius Plug-in
1048573,NY,Erie,2017-05-31,Toyota Prius Plug-in
1048574,NY,Rockland,2017-04-13,Toyota Prius Plug-in

In [12]:
  #export to postgres 

db_string = f"postgresql://TomS:projectToms@dataviz.cp48egzju3un.us-east-1.rds.amazonaws.com:5432/Electric"
engine = create_engine(db_string)
conn = engine.connect()

OperationalError: (psycopg2.OperationalError) connection to server at "dataviz.cp48egzju3un.us-east-1.rds.amazonaws.com" (44.195.112.244), port 5432 failed: FATAL:  password authentication failed for user "TomS"
connection to server at "dataviz.cp48egzju3un.us-east-1.rds.amazonaws.com" (44.195.112.244), port 5432 failed: FATAL:  password authentication failed for user "TomS"

(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [ ]:
# new_nj_county_df.to_sql(name='ev_registration', con=conn, if_exists='append', index=False)